UrlShortner/config/routes.rb
Rails.application.routes.draw do
  resources :links
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  devise_scope :user do
    delete "/users/sign_out" => "devise/sessions#destroy"
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
  match "/apikey", to: "home#showkey", via: :get
  match "/updatekey", to: "home#updatekey", via: :get
  match "/u/:shortcode", to: "home#redirect_shortcode", via: :get
end

UrlShortner/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

UrlShortner/app/models/link.rb
class Link < ApplicationRecord
  belongs_to :user

  validates :user, :source_link, presence: true
  validates_uniqueness_of :source_link, :shortcode
  validate :check_if_source_link_is_valid_url
  validate :generate_short_code, on: :create
  before_create :generate_short_code


  
  def check_if_source_link_is_valid_url
    invalid_url = true
    begin
      uri = URI.parse(self.source_link)
      invalid_url = false
    rescue URI::InvalidURIError
      invalid_url = true
    end
    
    if invalid_url
      errors.add(:source_link, "is not a valid URL")
    end
  end

  def generate_short_code
    failed_to_create_short_code = false
    begin
      retries ||= 0
      chars = ['0'..'9', 'A'..'Z', 'a'..'z'].map { |range| range.to_a }.flatten
      self.shortcode = 6.times.map { chars.sample }.join
      if List.exists?(shortcode: self.shortcode)
        failed_to_create_short_code = true
        raise
      else
        failed_to_create_short_code = false
      end
    rescue
      retry if (retries += 1) < 100
    end
    if failed_to_create_short_code
      errors.add(:source_link, "Unable to generate short code, please try again later")
    end
  end
end

UrlShortner/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :omniauthable, omniauth_providers: %i[google_oauth2]
  has_many :links

  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(email: data['email']).first
    
    # Uncomment the section below if you want users to be created if they don't exist
    unless user
      user = User.create(email: data['email'], name: data['name'])
    end
    user
  end
end

UrlShortner/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

UrlShortner/app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, except: [:redirect_shortcode, :index]
  
  def index
  end

  def showkey
  end

  def updatekey
    current_user.key = SecureRandom.uuid
    if current_user.save!
      flash[:notice] = "Key was successfully updated."
    else
      flash[:notice] = "Unable to update key."
    end
    redirect_to apikey_url
    return
  end

  def redirect_shortcode
    if params[:shortcode].present?
      @link = Link.where(shortcode: params[:shortcode]).first
      if @link.present?
        redirect_to @link.source_link
      else
        @error = "Can't find the URL, please check your link"
      end
    end
  end
end

UrlShortner/app/controllers/links_controller.rb
class LinksController < ApplicationController
  skip_before_action :verify_authenticity_token, if: :json_request?
  before_action :login_wrapper
  before_action :set_link, only: [:show, :edit, :update, :destroy]

  # GET /links
  # GET /links.json
  def index
    @links = current_user.links
  end

  # GET /links/1
  # GET /links/1.json
  def show
  end

  # GET /links/new
  def new
    @link = Link.new
    @link.user = current_user
  end

  # POST /links
  # POST /links.json
  def create
    @link = Link.new(link_params)
    @link.user = current_user

    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url, notice: 'Link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_link
    @link = Link.find(params[:id])
  end
  
  # Never trust parameters from the scary internet, only allow the white list through.
  def link_params
    if json_request?
      params.permit(:source_link)
    else
      params.require(:link).permit(:source_link, :key)
    end
  end

  def json_params
    params.permit(:key)
  end
  
  def login_wrapper
    if request.format.json?
      if json_params[:key].present?
        keybased_user = User.where(key: json_params[:key]).first
        if keybased_user.present?
          sign_in(:user, keybased_user)
        else
          return invalid_login_attempt
        end
      else
        return invalid_login_attempt
      end
    else
      authenticate_user!
    end
  end

  def invalid_login_attempt
    warden.custom_failure!
    render :json=> {:success=>false, :message=>"Error with your login or password"}, :status=>401
  end

  def json_request?
    request.format.json?
  end
end

UrlShortner/app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env['omniauth.auth'])
    
    if @user.persisted?
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
      sign_in_and_redirect @user, event: :authentication
    else
      session['devise.google_data'] = request.env['omniauth.auth'].except(:extra) # Removing extra as it can overflow some session stores
      redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
    end
  end

  def failure
    redirect_to root_path
  end
end

UrlShortner/app/helpers/application_helper.rb
module ApplicationHelper
end

UrlShortner/app/helpers/home_helper.rb
module HomeHelper
end

UrlShortner/app/helpers/links_helper.rb
module LinksHelper
end

UrlShortner/app/views/home/redirect_shortcode.html.erb
<% if @error %>
  <%= @error %>
<% end %>

UrlShortner/app/views/home/showkey.html.erb
<br><br><br>

Your key is <%= current_user.key || "not set" %>

<br>

<%= link_to "#{current_user.key.present? ? 'Update' : 'Set'} your API key", updatekey_path %>

UrlShortner/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrlShortner</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <% if current_user %>
      <%= link_to "Sign out", users_sign_out_path, method: :delete %>
      <br>
      <%= link_to "Your URLs", links_path %>
      <br>
      <%= link_to "API key", apikey_path %>
      <br>
      Signed in as <strong><%= current_user.name %></strong>!
    <% else %>
      <%= link_to "Sign in with Google", user_google_oauth2_omniauth_authorize_path %>
    <% end %>

    <%= yield %>
  </body>
</html>

UrlShortner/app/views/links/_form.html.erb
<%= form_with(model: link, local: true) do |form| %>
  <% if link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= form.label :source_link %>
    <%= form.text_area :source_link %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

UrlShortner/app/views/links/edit.html.erb
<h1>Editing Link</h1>

<%= render 'form', link: @link %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

UrlShortner/app/views/links/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Links</h1>

<table>
  <thead>
    <tr>
      <th>Shorturl</th>
      <th>Source link</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @links.each do |link| %>
      <tr>
        <td><%= "#{root_url}u/#{link.shortcode}" %></td>
        <td><%= link.source_link %></td>
        <td><%= link_to 'Show', link %></td>
        <td><%= link_to 'Destroy', link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Link', new_link_path %>

UrlShortner/app/views/links/new.html.erb
<h1>New Link</h1>

<%= render 'form', link: @link %>

<%= link_to 'Back', links_path %>

UrlShortner/app/views/links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @link.user_id %>
</p>

<p>
  <strong>Short URL:</strong>
  <%= "#{root_url}u/#{@link.shortcode}" %>
</p>

<p>
  <strong>Source link:</strong>
  <%= @link.source_link %>
</p>

<%= link_to 'Edit', edit_link_path(@link) %> |
<%= link_to 'Back', links_path %>